import { readFile } from "node:fs/promises";
import path from "node:path";

import { buildsCatalogDocument, catalogPath } from "./generate-catalog.ts";
import { buildsGeneratedTypes, repositoryRoot } from "./generate-types.ts";

/**
 * Proves committed generated artifacts still match their sources.
 *
 * Generated bytes are part of the trust chain: a stale catalog would admit a
 * digest nobody verified. This check fails loudly rather than regenerating,
 * so drift is a decision the author makes, not one a build makes silently.
 */
async function checksGeneratedArtifacts(): Promise<readonly string[]> {
  const drifted: string[] = [];

  const expectedCatalog = await buildsCatalogDocument();
  const actualCatalog = await readsOrEmpty(catalogPath);
  if (actualCatalog !== expectedCatalog) {
    drifted.push(path.relative(repositoryRoot, catalogPath));
  }

  for (const artifact of await buildsGeneratedTypes()) {
    const actual = await readsOrEmpty(artifact.outputPath);
    if (actual !== artifact.contents) {
      drifted.push(path.relative(repositoryRoot, artifact.outputPath));
    }
  }

  return drifted;
}

async function readsOrEmpty(filePath: string): Promise<string> {
  try {
    return (await readFile(filePath)).toString("utf8");
  } catch {
    return "";
  }
}

const drifted = await checksGeneratedArtifacts();

if (drifted.length > 0) {
  process.stderr.write(
    `Generated artifacts are stale:\n${drifted.map((entry) => `  ${entry}`).join("\n")}\n\n` +
      `Run "pnpm generate:catalog" and "pnpm generate:types", then commit the result.\n`
  );
  process.exitCode = 1;
} else {
  process.stdout.write("Generated artifacts are current.\n");
}
